# Ensure that this file do not contain non-ascii characters
# as flake8 can fail to parse the file on OS X and Windows

[tox]
skipsdist = True
setupdir={toxinidir}
envlist =
    3.10
    type
    docs

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
usedevelop = True
deps = 
    -e./src/
commands = pytest

[testenv:type]
runner = uv-venv-lock-runner
description = run type checker via mypy
with_dev = True
commands =
    mypy {posargs:./src}

[testenv:docs]
runner = uv-venv-lock-runner
description = generate docs
dependency_groups = 
    docs
commands =
    sphinx-build docs

[gh]
python =
    3.10 = 3.10

[pytest]
norecursedirs = tests/* .venv/* .tox/* build/ docs/