name: "Run Python tests"

on:
  pull_request:
  workflow_dispatch:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.10 tox --with tox-uv --with tox-gh
    
      - name: Run tests
        run: |
          pip install -r src/tests/requirements.txt
          tox
