name: "Bump Version Tag"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - .github/renovate.json
      - README.MD
      - LICENSE
      - docs/
      - src/restic_compose_backup/__init__.py # version bumps
  workflow_dispatch:

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get next version
        id: version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          WITH_V: true
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: Bump version in files
        run: |
          version="${{ steps.version.outputs.new_tag }}"
          clean_version="${version#v}"
          sed -i "s/__version__ = .*/__version__ = \"${clean_version}\"/" src/restic_compose_backup/__init__.py
          sed -i "s/release = .*/release = \"${clean_version}\"/" docs/conf.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: automated version bump

      - name: Push version tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          CUSTOM_TAG: ${{ steps.version.outputs.new_tag }}
